<#
.SYNOPSIS
  Traceability join + orphan report across the requirement/test registries, and
  regeneration of the architecture module map. The matrix is a GENERATED VIEW of
  the CSVs (see docs/process.md S4) -- never hand-maintained.

.DESCRIPTION
  Joins docs/requirements/system-requirements.csv, low-level-requirements.csv,
  and docs/test/test-cases.csv on their ID/parent columns. Writes
  docs/test/report.md and regenerates the module map in docs/architecture.md.

.PARAMETER Strict
  Exit non-zero if any orphan is found (used by the Objective 2 gate).
#>
[CmdletBinding()]
param([switch]$Strict)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$docs = Join-Path $repo 'docs'

function Load($rel) {
    $p = Join-Path $docs $rel
    if (-not (Test-Path $p)) { return @() }
    # Drop EXAMPLE placeholder rows (IDs ending in -000).
    Import-Csv $p | Where-Object { $_.PSObject.Properties.Value -notcontains $null }
}

$srs  = Load 'requirements\system-requirements.csv'  | Where-Object { $_.'SR-ID'  -and $_.'SR-ID'  -ne 'SR-000' }
$llrs = Load 'requirements\low-level-requirements.csv'| Where-Object { $_.'LLR-ID' -and $_.'LLR-ID' -ne 'LLR-000' }
$tcs  = Load 'test\test-cases.csv'                   | Where-Object { $_.'TC-ID'  -and $_.'TC-ID'  -ne 'TC-000' }

function Refs($s) { if ($s) { $s -split '[;, ]+' | Where-Object { $_ } } else { @() } }

$llrSrRefs = $llrs | ForEach-Object { Refs $_.'SR-Refs' } | Sort-Object -Unique
$tcRefs    = $tcs  | ForEach-Object { Refs $_.'Verifies' } | Sort-Object -Unique

$orphans = New-Object System.Collections.Generic.List[string]

foreach ($sr in $srs) {
    $id = $sr.'SR-ID'
    $isAnalytic = $sr.Verification -in @('Analysis','Inspection')
    if (-not $isAnalytic -and $llrSrRefs -notcontains $id) { $orphans.Add("SR $id has no LLR (and Verification != Analysis/Inspection)") }
    if ($tcRefs -notcontains $id) { $orphans.Add("SR $id has no test (TC)") }
}
$srIds = $srs.'SR-ID'
foreach ($llr in $llrs) {
    $id = $llr.'LLR-ID'
    $parents = Refs $llr.'SR-Refs'
    if (-not $parents) { $orphans.Add("LLR $id has no SR parent") }
    foreach ($p in $parents) { if ($srIds -notcontains $p) { $orphans.Add("LLR $id references unknown $p") } }
    if ($tcRefs -notcontains $id) { $orphans.Add("LLR $id has no test (TC)") }
}
$validIds = @($srIds) + @($llrs.'LLR-ID')
foreach ($tc in $tcs) {
    $v = Refs $tc.'Verifies'
    if (-not $v) { $orphans.Add("TC $($tc.'TC-ID') verifies nothing") }
    foreach ($r in $v) { if ($validIds -notcontains $r) { $orphans.Add("TC $($tc.'TC-ID') references unknown $r") } }
}

# --- write report ---
$report = Join-Path $docs 'test\report.md'
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# Coverage & Traceability Report")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("_Generated by ``scripts/trace.ps1`` on $(Get-Date -Format 'yyyy-MM-dd HH:mm'). Do not edit by hand._ See [process.md](../process.md).")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Metric | Count |")
[void]$sb.AppendLine("|---|---|")
[void]$sb.AppendLine("| System requirements (SR) | $($srs.Count) |")
[void]$sb.AppendLine("| Low-level requirements (LLR) | $($llrs.Count) |")
[void]$sb.AppendLine("| Test cases (TC) | $($tcs.Count) |")
[void]$sb.AppendLine("| Orphans | $($orphans.Count) |")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## SR -> LLR -> TC matrix")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| SR | LLRs | TCs | Status |")
[void]$sb.AppendLine("|---|---|---|---|")
foreach ($sr in $srs) {
    $id = $sr.'SR-ID'
    $l = ($llrs | Where-Object { (Refs $_.'SR-Refs') -contains $id }).'LLR-ID' -join ' '
    $t = ($tcs  | Where-Object { (Refs $_.'Verifies') -contains $id }).'TC-ID' -join ' '
    [void]$sb.AppendLine("| $id | $l | $t | $($sr.Status) |")
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Orphans")
[void]$sb.AppendLine("")
if ($orphans.Count -eq 0) { [void]$sb.AppendLine("None. Full coverage.") }
else { foreach ($o in $orphans) { [void]$sb.AppendLine("- $o") } }
Set-Content -Path $report -Value $sb.ToString() -Encoding UTF8

# --- regenerate architecture module map ---
$arch = Join-Path $docs 'architecture.md'
if (Test-Path $arch) {
    $map = [System.Text.StringBuilder]::new()
    [void]$map.AppendLine("<!-- BEGIN GENERATED MODULE MAP (scripts/trace.ps1) -->")
    [void]$map.AppendLine("_Generated $(Get-Date -Format 'yyyy-MM-dd'). Public items by module:_")
    [void]$map.AppendLine("")
    Get-ChildItem (Join-Path $repo 'src') -Recurse -Filter *.rs | Sort-Object FullName | ForEach-Object {
        $rel = $_.FullName.Substring($repo.Length + 1).Replace('\','/')
        $pubs = Select-String -Path $_.FullName -Pattern '^\s*pub\s+(fn|struct|enum|trait)\s+\w+' |
                ForEach-Object { ($_.Line.Trim() -replace '\s*\{.*$','') } | Select-Object -First 12
        if ($pubs) {
            [void]$map.AppendLine("- **$rel**")
            foreach ($p in $pubs) { [void]$map.AppendLine("  - ``$p``") }
        }
    }
    [void]$map.AppendLine("<!-- END GENERATED MODULE MAP -->")
    $content = Get-Content $arch -Raw
    $pattern = '(?s)<!-- BEGIN GENERATED MODULE MAP.*?<!-- END GENERATED MODULE MAP -->'
    $content = [regex]::Replace($content, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $map.ToString().TrimEnd() })
    Set-Content -Path $arch -Value $content -Encoding UTF8
}

Write-Host "Traceability: SR=$($srs.Count) LLR=$($llrs.Count) TC=$($tcs.Count) orphans=$($orphans.Count). Report -> docs/test/report.md"
if ($Strict -and $orphans.Count -gt 0) { exit 1 }
exit 0
