<#
.SYNOPSIS
  Traceability join + orphan report across the requirement/test registries, and
  regeneration of the architecture module map. The matrix is a GENERATED VIEW of
  the CSVs (see docs/process.md S4) -- never hand-maintained.

.DESCRIPTION
  Joins docs/requirements/system-requirements.csv, low-level-requirements.csv,
  and docs/test/test-cases.csv on their ID/parent columns. Writes
  docs/test/report.md and regenerates the module map in docs/architecture.md.

.PARAMETER Strict
  Exit non-zero if any orphan is found (used by the Objective 2 gate).
#>
[CmdletBinding()]
param([switch]$Strict)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$docs = Join-Path $repo 'docs'

function Load($rel) {
    $p = Join-Path $docs $rel
    if (-not (Test-Path $p)) { return @() }
    # Drop EXAMPLE placeholder rows (IDs ending in -000).
    Import-Csv $p | Where-Object { $_.PSObject.Properties.Value -notcontains $null }
}

$srs  = Load 'requirements\system-requirements.csv'  | Where-Object { $_.'SR-ID'  -and $_.'SR-ID'  -ne 'SR-000' }
$llrs = Load 'requirements\low-level-requirements.csv'| Where-Object { $_.'LLR-ID' -and $_.'LLR-ID' -ne 'LLR-000' }
$tcs  = Load 'test\test-cases.csv'                   | Where-Object { $_.'TC-ID'  -and $_.'TC-ID'  -ne 'TC-000' }

function Refs($s) { if ($s) { $s -split '[;, ]+' | Where-Object { $_ } } else { @() } }

$llrSrRefs = $llrs | ForEach-Object { Refs $_.'SR-Refs' } | Sort-Object -Unique
$tcRefs    = $tcs  | ForEach-Object { Refs $_.'Verifies' } | Sort-Object -Unique

$orphans = New-Object System.Collections.Generic.List[string]

foreach ($sr in $srs) {
    $id = $sr.'SR-ID'
    $isAnalytic = $sr.Verification -in @('Analysis','Inspection')
    if (-not $isAnalytic -and $llrSrRefs -notcontains $id) { $orphans.Add("SR $id has no LLR (and Verification != Analysis/Inspection)") }
    if ($tcRefs -notcontains $id) { $orphans.Add("SR $id has no test (TC)") }
}
$srIds = $srs.'SR-ID'
foreach ($llr in $llrs) {
    $id = $llr.'LLR-ID'
    $parents = Refs $llr.'SR-Refs'
    if (-not $parents) { $orphans.Add("LLR $id has no SR parent") }
    foreach ($p in $parents) { if ($srIds -notcontains $p) { $orphans.Add("LLR $id references unknown $p") } }
    if ($tcRefs -notcontains $id) { $orphans.Add("LLR $id has no test (TC)") }
}
$validIds = @($srIds) + @($llrs.'LLR-ID')
foreach ($tc in $tcs) {
    $v = Refs $tc.'Verifies'
    if (-not $v) { $orphans.Add("TC $($tc.'TC-ID') verifies nothing") }
    foreach ($r in $v) { if ($validIds -notcontains $r) { $orphans.Add("TC $($tc.'TC-ID') references unknown $r") } }
}

# --- write report ---
$report = Join-Path $docs 'test\report.md'
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# Coverage & Traceability Report")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("_Generated by ``scripts/trace.ps1`` on $(Get-Date -Format 'yyyy-MM-dd HH:mm'). Do not edit by hand._ See [process.md](../process.md).")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Metric | Count |")
[void]$sb.AppendLine("|---|---|")
[void]$sb.AppendLine("| System requirements (SR) | $($srs.Count) |")
[void]$sb.AppendLine("| Low-level requirements (LLR) | $($llrs.Count) |")
[void]$sb.AppendLine("| Test cases (TC) | $($tcs.Count) |")
[void]$sb.AppendLine("| Orphans | $($orphans.Count) |")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## SR -> LLR -> TC matrix")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| SR | LLRs | TCs | Status |")
[void]$sb.AppendLine("|---|---|---|---|")
foreach ($sr in $srs) {
    $id = $sr.'SR-ID'
    $l = ($llrs | Where-Object { (Refs $_.'SR-Refs') -contains $id }).'LLR-ID' -join ' '
    $t = ($tcs  | Where-Object { (Refs $_.'Verifies') -contains $id }).'TC-ID' -join ' '
    [void]$sb.AppendLine("| $id | $l | $t | $($sr.Status) |")
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Orphans")
[void]$sb.AppendLine("")
if ($orphans.Count -eq 0) { [void]$sb.AppendLine("None. Full coverage.") }
else { foreach ($o in $orphans) { [void]$sb.AppendLine("- $o") } }
Set-Content -Path $report -Value $sb.ToString() -Encoding UTF8

# --- regenerate architecture module map + dependency diagram ---
# Mirrors the project-trajectory kit's gen_arch_map.py conventions for Rust:
# per-file summary (first `//!` line), internal `crate::` dependencies, public
# items with `Implements:` back-links, and a Mermaid graph of the module deps.
$arch = Join-Path $docs 'architecture.md'
if (Test-Path $arch) {
    $srcRoot = Join-Path $repo 'src'
    $files = Get-ChildItem $srcRoot -Recurse -Filter *.rs | Sort-Object FullName

    # Top-level module of a file: src/foo.rs and src/foo/*.rs both -> foo.
    function TopModule($file) {
        $rel = $file.FullName.Substring($srcRoot.Length + 1).Replace('\','/')
        return ($rel.Split('/')[0] -replace '\.rs$','')
    }
    $modNames = @($files | ForEach-Object { TopModule $_ } | Sort-Object -Unique)

    $map = [System.Text.StringBuilder]::new()
    [void]$map.AppendLine("<!-- BEGIN GENERATED MODULE MAP (scripts/trace.ps1) -->")
    [void]$map.AppendLine("_Generated $(Get-Date -Format 'yyyy-MM-dd') by ``scripts/trace.ps1`` from the source tree — do not edit by hand. Each file's summary is its first ``//!`` line; ``<- SR/LLR`` are the ``Implements:`` back-links found at the item; ``uses:`` lists in-tree modules the file references (``crate::``)._")
    [void]$map.AppendLine("")

    $edges = @{}        # "from|to" between top-level modules, for the diagram
    $modSummary = @{}   # top-level module -> first summary seen (its mod.rs sorts first)
    foreach ($f in $files) {
        $rel = $f.FullName.Substring($repo.Length + 1).Replace('\','/')
        $lines = @(Get-Content $f.FullName)
        $top = TopModule $f

        $summary = ($lines | Where-Object { $_ -match '^\s*//!' } | Select-Object -First 1) -replace '^\s*//!\s?',''
        # The module's diagram label prefers its root file (src/<top>/mod.rs or
        # src/<top>.rs) over whichever child file happens to sort first.
        $isModRoot = $rel -in @("src/$top/mod.rs", "src/$top.rs")
        if ($summary -and ($isModRoot -or -not $modSummary.ContainsKey($top))) { $modSummary[$top] = $summary }

        # Internal deps: any `crate::<mod>` path naming another scanned top module.
        $uses = $lines | ForEach-Object {
            foreach ($m in [regex]::Matches($_, 'crate::(\w+)')) { $m.Groups[1].Value }
        } | Where-Object { $modNames -contains $_ -and $_ -ne $top } | Sort-Object -Unique
        foreach ($u in $uses) { $edges["$top|$u"] = $true }

        # Public items + the SR/LLR ids annotated in the few lines just above each.
        $pubs = @()
        for ($i = 0; $i -lt $lines.Count; $i++) {
            if ($lines[$i] -match '^\s*pub\s+(fn|struct|enum|trait)\s+\w+') {
                $decl = ($lines[$i].Trim() -replace '\s*\{.*$','')
                $ids = @()
                for ($j = [Math]::Max(0, $i - 6); $j -lt $i; $j++) {
                    if ($lines[$j] -match '^\s*(//|#\[)') {
                        $ids += [regex]::Matches($lines[$j], '\b(?:SR|LLR)-\d+\b') | ForEach-Object { $_.Value }
                    }
                }
                $pubs += [pscustomobject]@{ Decl = $decl; Ids = @($ids | Sort-Object -Unique) }
            }
        }
        if (-not ($summary -or $pubs)) { continue }
        $head = "- **$rel**"
        if ($summary) { $head += " — _${summary}_" }
        [void]$map.AppendLine($head)
        if ($uses) { [void]$map.AppendLine("  - uses: " + (($uses | ForEach-Object { '`' + $_ + '`' }) -join ', ')) }
        foreach ($p in @($pubs | Select-Object -First 12)) {
            $suffix = if ($p.Ids) { '  <- ' + ($p.Ids -join ', ') } else { '' }
            [void]$map.AppendLine("  - ``$($p.Decl)``$suffix")
        }
    }
    [void]$map.AppendLine("<!-- END GENERATED MODULE MAP -->")

    # Mermaid dependency diagram (top-level module granularity); spliced only if
    # architecture.md carries the marker pair, mirroring the kit's optional block.
    $dg = [System.Text.StringBuilder]::new()
    [void]$dg.AppendLine("<!-- BEGIN GENERATED DEPENDENCY DIAGRAM (scripts/trace.ps1) -->")
    [void]$dg.AppendLine("_Generated by ``scripts/trace.ps1``: each arrow is a ``crate::`` reference between top-level modules. Do not edit by hand._")
    [void]$dg.AppendLine("")
    [void]$dg.AppendLine('```mermaid')
    [void]$dg.AppendLine('graph LR')
    foreach ($m in $modNames) {
        $label = $m
        if ($modSummary.ContainsKey($m)) {
            $s = $modSummary[$m] -replace '"',"'"
            if ($s.Length -gt 48) { $s = $s.Substring(0,47) + '…' }
            $label = "$m — $s"
        }
        [void]$dg.AppendLine("    m_$m[`"$label`"]")
    }
    foreach ($e in ($edges.Keys | Sort-Object)) {
        $from, $to = $e.Split('|')
        [void]$dg.AppendLine("    m_$from --> m_$to")
    }
    [void]$dg.AppendLine('```')
    [void]$dg.AppendLine("<!-- END GENERATED DEPENDENCY DIAGRAM -->")

    $content = Get-Content $arch -Raw
    $pattern = '(?s)<!-- BEGIN GENERATED MODULE MAP.*?<!-- END GENERATED MODULE MAP -->'
    $content = [regex]::Replace($content, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $map.ToString().TrimEnd() })
    $dgPattern = '(?s)<!-- BEGIN GENERATED DEPENDENCY DIAGRAM.*?<!-- END GENERATED DEPENDENCY DIAGRAM -->'
    if ($content -match $dgPattern) {
        $content = [regex]::Replace($content, $dgPattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $dg.ToString().TrimEnd() })
    }
    Set-Content -Path $arch -Value $content.TrimEnd() -Encoding UTF8
}

Write-Host "Traceability: SR=$($srs.Count) LLR=$($llrs.Count) TC=$($tcs.Count) orphans=$($orphans.Count). Report -> docs/test/report.md"
if ($Strict -and $orphans.Count -gt 0) { exit 1 }
exit 0
